spring.application.name=planetbooks

spring.datasource.url=jdbc:mysql://localhost:3306/books?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Send emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=planetbooks.pe@gmail.com
spring.mail.password=Planetbooks4312#@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
